-- Migration: Enable RLS on all tables
-- PHASE 4, STEP 13
-- Enable Row Level Security (RLS) on all main tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_management ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_management ENABLE ROW LEVEL SECURITY;
