#!/usr/bin/env tsx
/**
 * Inventory all Next.js API routes under app/api/**\/route.ts.
 *
 * Emits:
 *   docs/api-inventory.md   — grouped markdown table
 *   docs/api-inventory.json — machine-readable, feeds bruno + callgraph
 *
 * Run: npm run audit:routes
 */

import fs from 'node:fs';
import path from 'node:path';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const API_ROOT = path.join(REPO_ROOT, 'app', 'api');
const OUT_JSON = path.join(REPO_ROOT, 'docs', 'api-inventory.json');
const OUT_MD = path.join(REPO_ROOT, 'docs', 'api-inventory.md');

const HTTP_VERBS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'] as const;
type HttpVerb = (typeof HTTP_VERBS)[number];

interface RouteEntry {
  file: string;
  domain: string;
  path: string;
  methods: HttpVerb[];
  auth: {
    requiresUser: boolean;
    requiresAdminClient: boolean;
    requiresCronSecret: boolean;
    requiresApiKey: boolean;
    requiresServiceRole: boolean;
    roleChecks: string[];
  };
  schemas: string[];
  lines: number;
}

function walkRoutes(dir: string, acc: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkRoutes(full, acc);
    } else if (entry.isFile() && entry.name === 'route.ts') {
      acc.push(full);
    }
  }
  return acc;
}

function fileToRoutePath(file: string): string {
  const rel = path.relative(API_ROOT, path.dirname(file));
  if (rel === '') return '/api';
  const segments = rel
    .split(path.sep)
    .map((seg) =>
      seg.replace(/^\[(\.\.\.)?(.+?)\]$/, (_, spread, name) => (spread ? `*${name}` : `:${name}`))
    );
  return '/api/' + segments.join('/');
}

function routeToDomain(routePath: string): string {
  const parts = routePath.replace(/^\/api\/?/, '').split('/');
  return parts[0] || 'root';
}

function analyseFile(file: string): RouteEntry {
  const source = fs.readFileSync(file, 'utf8');
  const lines = source.split('\n').length;

  const methods: HttpVerb[] = [];
  for (const verb of HTTP_VERBS) {
    const re = new RegExp(`export\\s+(async\\s+)?function\\s+${verb}\\b`);
    if (re.test(source)) methods.push(verb);
  }

  const schemas = Array.from(source.matchAll(/from\s+['"]@\/schemas\/([^'"]+)['"]/g), (m) => m[1]);

  const roleChecks: string[] = [];
  for (const role of ['admin', 'teacher', 'student']) {
    const re = new RegExp(
      `\\b(is${role[0].toUpperCase()}${role.slice(1)}|requireRole\\(['"]${role}['"]\\)|role\\s*===?\\s*['"]${role}['"])\\b`
    );
    if (re.test(source)) roleChecks.push(role);
  }

  const auth = {
    requiresUser: /\bwithApiAuth\b|\brequireAuth\b|\bauthenticateRequest\b|\bcreateClient\b/.test(
      source
    ),
    requiresAdminClient: /\bcreateAdminClient\b/.test(source),
    requiresCronSecret: /\bverifyCronSecret\b|\bCRON_SECRET\b/.test(source),
    requiresApiKey:
      /\bverifyApiKey\b|\bauthenticateWithBearerToken\b|\bextractBearerToken\b|\bx-api-key\b/i.test(
        source
      ),
    requiresServiceRole: /\bSUPABASE_SERVICE_ROLE_KEY\b|\bSERVICE_ROLE_KEY\b/.test(source),
    roleChecks,
  };

  const routePath = fileToRoutePath(file);
  return {
    file: path.relative(REPO_ROOT, file),
    domain: routeToDomain(routePath),
    path: routePath,
    methods,
    auth,
    schemas: [...new Set(schemas)],
    lines,
  };
}

function buildMarkdown(routes: RouteEntry[]): string {
  const grouped = new Map<string, RouteEntry[]>();
  for (const r of routes) {
    const arr = grouped.get(r.domain) ?? [];
    arr.push(r);
    grouped.set(r.domain, arr);
  }
  const domains = [...grouped.keys()].sort();

  const totalMethods = routes.reduce((n, r) => n + r.methods.length, 0);
  const totalLines = routes.reduce((n, r) => n + r.lines, 0);

  const header = [
    '# API Inventory',
    '',
    `> Generated by \`npm run audit:routes\`. Do not edit by hand.`,
    '',
    `- **Total route files**: ${routes.length}`,
    `- **Total HTTP method handlers**: ${totalMethods}`,
    `- **Total LOC**: ~${totalLines.toLocaleString()}`,
    `- **Domains**: ${domains.length}`,
    '',
  ];

  const sections: string[] = [];
  for (const domain of domains) {
    const items = grouped.get(domain)!.sort((a, b) => a.path.localeCompare(b.path));
    sections.push(`## ${domain} (${items.length} routes)`);
    sections.push('');
    sections.push('| Method | Path | Auth | Schemas | LOC |');
    sections.push('|---|---|---|---|---|');
    for (const r of items) {
      const authParts: string[] = [];
      if (r.auth.requiresCronSecret) authParts.push('cron-secret');
      if (r.auth.requiresApiKey) authParts.push('api-key');
      if (r.auth.requiresServiceRole) authParts.push('service-role');
      if (r.auth.requiresAdminClient) authParts.push('admin-client');
      if (r.auth.requiresUser) authParts.push('user');
      if (r.auth.roleChecks.length) authParts.push(`role:${r.auth.roleChecks.join('+')}`);
      const authStr = authParts.join(', ') || '_none_';
      const methodStr = r.methods.join(', ') || '_none_';
      const schemaStr = r.schemas.length ? r.schemas.join(', ') : '—';
      sections.push(`| ${methodStr} | \`${r.path}\` | ${authStr} | ${schemaStr} | ${r.lines} |`);
    }
    sections.push('');
  }

  return header.concat(sections).join('\n');
}

function main(): void {
  if (!fs.existsSync(API_ROOT)) {
    console.error(`API root not found: ${API_ROOT}`);
    process.exit(1);
  }

  const files = walkRoutes(API_ROOT).sort();
  const routes = files.map(analyseFile);

  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(
    OUT_JSON,
    JSON.stringify({ generatedAt: new Date().toISOString(), routes }, null, 2)
  );
  fs.writeFileSync(OUT_MD, buildMarkdown(routes));

  const verbCount = routes.reduce((n, r) => n + r.methods.length, 0);
  console.log(`Inventory: ${routes.length} route files, ${verbCount} HTTP handlers.`);
  console.log(`  → ${path.relative(REPO_ROOT, OUT_JSON)}`);
  console.log(`  → ${path.relative(REPO_ROOT, OUT_MD)}`);
}

main();
