/**
 * Renders the demo studio as a single idempotent SQL script.
 *
 * `seed-demo.ts` is the normal path and writes over PostgREST with a
 * service-role key. That path is unavailable on a self-hosted stack whose key
 * you cannot read — which is exactly the situation on `uwh`, where the only
 * channel to StudentProduction is `docker exec … psql`. Rather than maintain a
 * second copy of the dataset (the drift `.claude/rules/structure.md` S4 is
 * about), both transports read `demo-studio.data.ts` and this one prints SQL.
 *
 *   npx tsx scripts/database/seeding/demo/emit-demo-sql.ts > /tmp/demo.sql
 *   docker exec -i supabase_db_StudentProduction psql -U postgres -d postgres < /tmp/demo.sql
 *
 * Every timestamp is resolved here, not in SQL, so the output is a plain data
 * script with no date arithmetic to get subtly wrong in two languages. The only
 * things left for the database to resolve are the ids it alone knows: profile
 * ids (by email) and song ids (by title).
 */

import {
  ASSIGNMENTS_BY_STUDENT,
  DEMO_NOTIFICATIONS,
  DEMO_PASSWORD,
  DEMO_SONGS,
  DEMO_SONG_REQUESTS,
  DEMO_USERS,
  LESSON_SONGS_BY_STUDENT,
  PRACTICE_PLAN,
  SELF_RATINGS,
  SONG_OF_THE_WEEK,
  STUDENT_LESSONS,
  THIS_WEEK_SCHEDULE,
  lessonTitleFromNotes,
} from './demo-studio.data';

// ─── SQL literal helpers ──────────────────────────────────────────────────────

const NULL = 'null';

/** Single-quoted literal with doubled quotes. */
function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return NULL;
  return `'${value.replace(/'/g, "''")}'`;
}

/** Dollar-quoted, for song lyrics: multi-line text full of punctuation. */
function longLit(value: string | null | undefined): string {
  if (value === null || value === undefined) return NULL;
  let tag = 'demo';
  while (value.includes(`$${tag}$`)) tag += 'x';
  return `$${tag}$${value}$${tag}$`;
}

function num(value: number | null | undefined): string {
  return value === null || value === undefined ? NULL : String(value);
}

function bool(value: boolean): string {
  return value ? 'true' : 'false';
}

function ts(date: Date): string {
  return `'${date.toISOString()}'::timestamptz`;
}

function daysFromNow(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d;
}

function hoursAgo(hours: number): Date {
  return new Date(Date.now() - hours * 3_600_000);
}

const out: string[] = [];
const write = (line = '') => out.push(line);
const section = (title: string) => {
  write();
  write(`-- ${'═'.repeat(74)}`);
  write(`-- ${title}`);
  write(`-- ${'═'.repeat(74)}`);
};

const TEACHER = DEMO_USERS.find((u) => u.isTeacher)!;
const STUDENTS = DEMO_USERS.filter((u) => u.isStudent);

// ─── Preamble ─────────────────────────────────────────────────────────────────

write('-- GENERATED by scripts/database/seeding/demo/emit-demo-sql.ts — do not edit.');
write(`-- Generated at ${new Date().toISOString()}`);
write('--');
write("-- Idempotent: re-running replaces this cohort's demo content and leaves");
write('-- every other row in the database alone. Songs are never overwritten.');
write('\\set ON_ERROR_STOP on');
write('begin;');

section('Demo people');
write(
  'create temp table _people(email text primary key, full_name text, is_teacher boolean, is_student boolean) on commit drop;'
);
write('insert into _people (email, full_name, is_teacher, is_student) values');
write(
  DEMO_USERS.map(
    (u) => `  (${lit(u.email)}, ${lit(u.fullName)}, ${bool(u.isTeacher)}, ${bool(u.isStudent)})`
  ).join(',\n') + ';'
);

write();
write('-- Create any missing account through auth.users + auth.identities, the same');
write('-- pair GoTrue itself writes. The handle_new_user trigger fires on the insert');
write('-- and mints the profile, so it is never built by hand here.');
write('with created as (');
write('  insert into auth.users (id, instance_id, aud, role, email, encrypted_password,');
write(
  '                          email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)'
);
write("  select gen_random_uuid(), '00000000-0000-0000-0000-000000000000',");
write("         'authenticated', 'authenticated', p.email,");
write(`         crypt(${lit(DEMO_PASSWORD)}, gen_salt('bf')), now(),`);
write('         \'{"provider":"email","providers":["email"]}\'::jsonb,');
write("         jsonb_build_object('full_name', p.full_name), now(), now()");
write('    from _people p');
write('   where not exists (select 1 from auth.users u where u.email = p.email)');
write('  returning id, email');
write(')');
write(
  'insert into auth.identities (id, user_id, provider_id, provider, identity_data, created_at, updated_at, last_sign_in_at)'
);
write("select gen_random_uuid(), c.id, c.id::text, 'email',");
write(
  "       jsonb_build_object('sub', c.id::text, 'email', c.email, 'email_verified', true, 'phone_verified', false),"
);
write('       now(), now(), now()');
write('  from created c;');

write();
write('-- Reset the password on accounts that already existed, so the credentials');
write('-- printed on the sign-in button are always the ones that work.');
write('update auth.users u');
write(`   set encrypted_password = crypt(${lit(DEMO_PASSWORD)}, gen_salt('bf')),`);
write('       email_confirmed_at = coalesce(u.email_confirmed_at, now()),');
write('       updated_at = now()');
write('  from _people p');
write(' where u.email = p.email;');

write();
write('-- A profile may be missing even when the account is not: production has');
write('-- five demo accounts whose profiles were deleted, which is what left the');
write('-- public "Try the demo" button signing people into an onboarding loop.');
write(
  'insert into public.profiles (user_id, email, full_name, is_teacher, is_student, is_admin, is_development)'
);
write('select u.id, p.email, p.full_name, p.is_teacher, p.is_student, false, true');
write('  from _people p join auth.users u on u.email = p.email');
write(' where not exists (select 1 from public.profiles pr where pr.user_id = u.id);');

write();
write('update public.profiles pr');
write('   set email = p.email, full_name = p.full_name,');
write('       is_teacher = p.is_teacher, is_student = p.is_student,');
write('       is_admin = false, is_development = true,');
write("       avatar_url = 'https://i.pravatar.cc/150?u=' || p.email");
write('  from _people p join auth.users u on u.email = p.email');
write(' where pr.user_id = u.id;');

write();
write('create temp table _ids(email text primary key, profile_id uuid) on commit drop;');
write('insert into _ids (email, profile_id)');
write('select p.email, pr.id from _people p');
write('  join auth.users u on u.email = p.email');
write('  join public.profiles pr on pr.user_id = u.id;');

write();
write('do $guard$ begin');
write(
  `  if (select count(*) from _ids) <> ${DEMO_USERS.length} then raise exception 'expected ${DEMO_USERS.length} demo profiles, got %', (select count(*) from _ids); end if;`
);
write('end $guard$;');

// ─── Songs ────────────────────────────────────────────────────────────────────

section('Songs — link to the catalogue, fill only the gaps');
const SONG_COLUMNS = [
  'author',
  'level',
  'key',
  'tempo',
  'capo_fret',
  'chords',
  'strumming_pattern',
  'category',
  'release_year',
  'youtube_url',
  'spotify_link_url',
  'ultimate_guitar_link',
  'lyrics_with_chords',
] as const;

write(
  'create temp table _songs(title text primary key, author text, level text, key text, tempo int,'
);
write('  capo_fret int, chords text, strumming_pattern text, category text, release_year int,');
write(
  '  youtube_url text, spotify_link_url text, ultimate_guitar_link text, lyrics_with_chords text) on commit drop;'
);
write('insert into _songs values');
write(
  DEMO_SONGS.map((s) => {
    const row = s as Record<string, unknown>;
    return `  (${lit(s.title)}, ${lit(row.author as string)}, ${lit(row.level as string)}, ${lit(
      row.key as string
    )}, ${num(row.tempo as number)}, ${num(row.capo_fret as number)}, ${lit(
      row.chords as string
    )}, ${lit(row.strumming_pattern as string)}, ${lit(row.category as string)}, ${num(
      row.release_year as number
    )}, ${lit(row.youtube_url as string)}, ${lit(row.spotify_link_url as string)}, ${lit(
      row.ultimate_guitar_link as string
    )}, ${longLit(row.lyrics_with_chords as string)})`;
  }).join(',\n') + ';'
);

write();
write('-- Several catalogue rows can share a title. Take the richest one — that is');
write("-- the teacher's real entry — and never write over a column it already answers.");
write('create temp table _song_map(title text primary key, song_id uuid) on commit drop;');
write('insert into _song_map (title, song_id)');
write('select distinct on (s.title) s.title, s.id');
write('  from public.songs s join _songs d on d.title = s.title');
write(' where s.deleted_at is null');
write(
  ` order by s.title, num_nonnulls(${SONG_COLUMNS.map((c) => `s.${c}`).join(', ')}) desc, s.created_at asc;`
);

write();
write('insert into public.songs (title, author, level, key, tempo, capo_fret, chords,');
write('                          strumming_pattern, category, release_year, youtube_url,');
write('                          spotify_link_url, ultimate_guitar_link, lyrics_with_chords)');
write(
  'select d.title, d.author, d.level::public.difficulty_level, d.key::public.music_key, d.tempo,'
);
write('       d.capo_fret, d.chords, d.strumming_pattern, d.category, d.release_year,');
write('       d.youtube_url, d.spotify_link_url, d.ultimate_guitar_link, d.lyrics_with_chords');
write('  from _songs d');
write(' where not exists (select 1 from _song_map m where m.title = d.title);');

write();
write('insert into _song_map (title, song_id)');
write('select s.title, s.id from public.songs s join _songs d on d.title = s.title');
write(' where not exists (select 1 from _song_map m where m.title = s.title)');
write('on conflict (title) do nothing;');

write();
write('update public.songs s set');
write(
  SONG_COLUMNS.map((c) => {
    const cast =
      c === 'level' ? '::public.difficulty_level' : c === 'key' ? '::public.music_key' : '';
    return `  ${c} = coalesce(s.${c}, d.${c}${cast})`;
  }).join(',\n')
);
write('  from _songs d join _song_map m on m.title = d.title');
write(' where s.id = m.song_id;');

// ─── Wipe this cohort ─────────────────────────────────────────────────────────

section('Clear this cohort — never anybody else');
write('create temp table _students(profile_id uuid primary key) on commit drop;');
write(
  `insert into _students select profile_id from _ids where email in (${STUDENTS.map((s) => lit(s.email)).join(', ')});`
);
write();
write(
  'delete from public.practice_sessions where student_id in (select profile_id from _students);'
);
write('delete from public.song_requests where student_id in (select profile_id from _students);');
write('delete from public.in_app_notifications where profile_id in (select profile_id from _ids);');
write('delete from public.assignments where student_id in (select profile_id from _students);');
write('delete from public.lessons where student_id in (select profile_id from _students);');

// ─── Lessons ──────────────────────────────────────────────────────────────────

section('Lessons — completed history, then this week');
write(
  'create temp table _lessons(email text, idx int, number int, status text, scheduled_at timestamptz, title text, notes text) on commit drop;'
);

const lessonRows: string[] = [];
for (const student of STUDENTS) {
  const notes = STUDENT_LESSONS[student.email] ?? [];
  notes.forEach((lesson, i) => {
    const weeksAgo = notes.length - i;
    lessonRows.push(
      `  (${lit(student.email)}, ${i}, ${i + 1}, 'COMPLETED', ${ts(
        daysFromNow(-(weeksAgo * 7))
      )}, ${lit(lessonTitleFromNotes(lesson.notes))}, ${lit(lesson.notes)})`
    );
  });
}
write('insert into _lessons (email, idx, number, status, scheduled_at, title, notes) values');
write(lessonRows.join(',\n') + ';');

write();
write('-- Recover the generated ids by (student, scheduled_at): each historical');
write('-- lesson sits in its own week, so that pair is unique.');
write('create temp table _lesson_ids(email text, idx int, lesson_id uuid) on commit drop;');
write('with ins as (');
write(
  '  insert into public.lessons (teacher_id, student_id, lesson_teacher_number, status, scheduled_at, title, notes)'
);
write(`  select (select profile_id from _ids where email = ${lit(TEACHER.email)}), i.profile_id,`);
write('         l.number, l.status::public.lesson_status, l.scheduled_at, l.title, l.notes');
write('    from _lessons l join _ids i on i.email = l.email');
write('  returning id, student_id, scheduled_at');
write(')');
write('insert into _lesson_ids (email, idx, lesson_id)');
write('select l.email, l.idx, ins.id');
write('  from ins');
write('  join _ids i on i.profile_id = ins.student_id');
write('  join _lessons l on l.email = i.email and l.scheduled_at = ins.scheduled_at;');

// This week
const now = new Date();
const weekStart = new Date(now);
weekStart.setDate(now.getDate() - now.getDay());
weekStart.setHours(0, 0, 0, 0);

const weekRows = THIS_WEEK_SCHEDULE.map((l) => {
  const date = new Date(weekStart);
  date.setDate(weekStart.getDate() + l.dow);
  date.setHours(l.hour, 0, 0, 0);
  const isPast = l.dow < now.getDay() || (l.dow === now.getDay() && l.hour <= now.getHours());
  return `  (${lit(l.email)}, ${lit(isPast ? 'COMPLETED' : 'SCHEDULED')}, ${ts(date)}, ${lit(
    lessonTitleFromNotes(l.notes)
  )}, ${lit(l.notes)})`;
});

write();
write(
  'create temp table _week(email text, status text, scheduled_at timestamptz, title text, notes text) on commit drop;'
);
write('insert into _week (email, status, scheduled_at, title, notes) values');
write(weekRows.join(',\n') + ';');
write();
write('-- lesson_teacher_number 0 lets the numbering trigger own it, as the');
write('-- PostgREST seed does for this-week rows.');
write(
  'insert into public.lessons (teacher_id, student_id, lesson_teacher_number, status, scheduled_at, title, notes)'
);
write(`select (select profile_id from _ids where email = ${lit(TEACHER.email)}), i.profile_id,`);
write('       0, w.status::public.lesson_status, w.scheduled_at, w.title, w.notes');
write('  from _week w join _ids i on i.email = w.email;');

// ─── Lesson songs ─────────────────────────────────────────────────────────────

section('Lesson songs (student_repertoire follows by trigger)');
const lessonSongRows: string[] = [];
for (const student of STUDENTS) {
  const perLesson = LESSON_SONGS_BY_STUDENT[student.email] ?? [];
  perLesson.forEach((specs, idx) => {
    for (const spec of specs) {
      lessonSongRows.push(
        `  (${lit(student.email)}, ${idx}, ${lit(spec.title)}, ${lit(spec.status)})`
      );
    }
  });
}
write(
  'create temp table _lesson_songs(email text, idx int, title text, status text) on commit drop;'
);
write('insert into _lesson_songs (email, idx, title, status) values');
write(lessonSongRows.join(',\n') + ';');
write();
write('insert into public.lesson_songs (lesson_id, song_id, status)');
write('select li.lesson_id, m.song_id, ls.status::public.lesson_song_status');
write('  from _lesson_songs ls');
write('  join _lesson_ids li on li.email = ls.email and li.idx = ls.idx');
write('  join _song_map m on m.title = ls.title;');

// ─── Assignments ──────────────────────────────────────────────────────────────

section('Assignments');
const assignmentRows: string[] = [];
for (const student of STUDENTS) {
  for (const a of ASSIGNMENTS_BY_STUDENT[student.email] ?? []) {
    assignmentRows.push(
      `  (${lit(student.email)}, ${lit(a.title)}, ${lit(a.description)}, ${lit(a.status)}, ${ts(
        daysFromNow(a.dueDaysFromNow)
      )}::date)`
    );
  }
}
write(
  'create temp table _assignments(email text, title text, description text, status text, due_date date) on commit drop;'
);
write('insert into _assignments (email, title, description, status, due_date) values');
write(assignmentRows.join(',\n') + ';');
write();
write(
  'insert into public.assignments (teacher_id, student_id, title, description, status, due_date)'
);
write(`select (select profile_id from _ids where email = ${lit(TEACHER.email)}), i.profile_id,`);
write('       a.title, a.description, a.status::public.assignment_status, a.due_date');
write('  from _assignments a join _ids i on i.email = a.email;');

// ─── Practice ─────────────────────────────────────────────────────────────────

section('Practice sessions');
const practiceRows: string[] = [];
for (const student of STUDENTS) {
  const repertoire = (LESSON_SONGS_BY_STUDENT[student.email] ?? []).flat().map((s) => s.title);
  (PRACTICE_PLAN[student.email] ?? []).forEach((p, i) => {
    const at = new Date();
    at.setDate(at.getDate() - p.daysAgo);
    at.setHours(17, 30, 0, 0);
    const title = repertoire.length ? repertoire[i % repertoire.length] : null;
    practiceRows.push(
      `  (${lit(student.email)}, ${lit(title)}, ${num(p.minutes)}, ${num(p.bpm)}, ${lit(
        p.note
      )}, ${ts(at)})`
    );
  });
}
write(
  'create temp table _practice(email text, song_title text, minutes int, bpm int, note text, at timestamptz) on commit drop;'
);
write('insert into _practice (email, song_title, minutes, bpm, note, at) values');
write(practiceRows.join(',\n') + ';');
write();
write(
  'insert into public.practice_sessions (student_id, song_id, duration_minutes, bpm_practiced, notes, created_at)'
);
write('select i.profile_id, m.song_id, p.minutes, p.bpm, p.note, p.at');
write('  from _practice p');
write('  join _ids i on i.email = p.email');
write('  left join _song_map m on m.title = p.song_title;');

// ─── Self ratings ─────────────────────────────────────────────────────────────

section('Repertoire self-ratings');
write('create temp table _ratings(email text primary key, rating int, note text) on commit drop;');
write('insert into _ratings (email, rating, note) values');
write(
  STUDENTS.map((s) => {
    const cfg = SELF_RATINGS[s.email];
    return `  (${lit(s.email)}, ${num(cfg?.rating)}, ${lit(cfg?.note)})`;
  }).join(',\n') + ';'
);
write();
write('-- Mirrors the PostgREST seed: the three most recent repertoire rows, the');
write('-- rating stepping down by one, and the note only on the first.');
write('with ranked as (');
write(
  '  select sr.id, r.email, r.rating, r.note, row_number() over (partition by sr.student_id order by sr.created_at desc) as rn'
);
write('    from public.student_repertoire sr');
write('    join _ids i on i.profile_id = sr.student_id');
write('    join _ratings r on r.email = i.email');
write(')');
write('update public.student_repertoire sr');
write('   set self_rating = greatest(1, ranked.rating - (ranked.rn - 1)::int),');
write('       self_rating_updated_at = now(),');
write('       student_notes = case when ranked.rn = 1 then ranked.note else null end');
write('  from ranked where ranked.id = sr.id and ranked.rn <= 3;');

// ─── Notifications ────────────────────────────────────────────────────────────

section('In-app notifications');
write(
  'create temp table _notifications(email text, type text, title text, body text, priority int,'
);
write(
  '  is_read boolean, action_url text, action_label text, read_at timestamptz, created_at timestamptz) on commit drop;'
);
write(
  'insert into _notifications (email, type, title, body, priority, is_read, action_url, action_label, read_at, created_at) values'
);
write(
  DEMO_NOTIFICATIONS.map((n) => {
    const email = n.recipient === 'teacher' ? TEACHER.email : n.recipient;
    return `  (${lit(email)}, ${lit(n.type)}, ${lit(n.title)}, ${lit(n.body)}, ${num(
      n.priority
    )}, ${bool(n.isRead)}, ${lit(n.actionUrl)}, ${lit(n.actionLabel)}, ${
      n.readHoursAgo === undefined ? NULL : ts(hoursAgo(n.readHoursAgo))
    }, ${ts(hoursAgo(n.createdHoursAgo))})`;
  }).join(',\n') + ';'
);
write();
write(
  'insert into public.in_app_notifications (profile_id, notification_type, title, body, priority, is_read, action_url, action_label, read_at, created_at)'
);
write(
  'select i.profile_id, n.type::public.notification_type, n.title, n.body, n.priority, n.is_read,'
);
write('       n.action_url, n.action_label, n.read_at, n.created_at');
write('  from _notifications n join _ids i on i.email = n.email;');

// ─── Song of the week ─────────────────────────────────────────────────────────

section('Song of the week');
write('-- getCurrentSongOfTheWeek() uses maybeSingle(), so exactly one may be active.');
write('update public.song_of_the_week set is_active = false where is_active;');
write(
  'insert into public.song_of_the_week (song_id, selected_by, teacher_message, active_from, active_until, is_active, category)'
);
write(
  `select m.song_id, (select profile_id from _ids where email = ${lit(TEACHER.email)}), ${lit(
    SONG_OF_THE_WEEK.teacherMessage
  )},`
);
write(`       now(), ${ts(daysFromNow(SONG_OF_THE_WEEK.activeDays))}, true, 'student'`);
write(`  from _song_map m where m.title = ${lit(SONG_OF_THE_WEEK.songTitle)};`);

// ─── Song requests ────────────────────────────────────────────────────────────

section('Song requests');
write(
  'create temp table _requests(email text, title text, artist text, url text, notes text, status text, review_notes text, created_at timestamptz) on commit drop;'
);
write(
  'insert into _requests (email, title, artist, url, notes, status, review_notes, created_at) values'
);
write(
  DEMO_SONG_REQUESTS.map(
    (r) =>
      `  (${lit(r.student)}, ${lit(r.title)}, ${lit(r.artist)}, ${lit(r.url)}, ${lit(
        r.notes
      )}, ${lit(r.status)}, ${lit(r.reviewNotes)}, ${ts(hoursAgo(r.createdHoursAgo))})`
  ).join(',\n') + ';'
);
write();
write(
  'insert into public.song_requests (student_id, title, artist, url, notes, status, reviewed_by, review_notes, created_at)'
);
write('select i.profile_id, r.title, r.artist, r.url, r.notes, r.status,');
write(
  `       case when r.review_notes is null then null else (select profile_id from _ids where email = ${lit(TEACHER.email)}) end,`
);
write('       r.review_notes, r.created_at');
write('  from _requests r join _ids i on i.email = r.email;');

section('Done');
write('commit;');
write();

process.stdout.write(out.join('\n') + '\n');
