#!/usr/bin/env python3
"""Generate an idempotent SQL seed for the StudentDevelopment stack.

Produces a realistic small studio (shadow students + 2 teachers + lessons +
lesson_songs + repertoire + assignments) that REUSES the 15 existing songs, so
song/dashboard/role views stop being empty. Deterministic (fixed RNG seed) so the
committed .sql is stable. Emits to stdout.

Run:  python3 gen-dev-studio-seed.py > dev-studio-seed.sql
Then: ssh uwh "docker exec -i supabase_db_StudentDevelopment psql -U postgres \\
        -v ON_ERROR_STOP=1" < dev-studio-seed.sql

Idempotent: every row is tagged 'seed:dev-studio'; the script deletes prior seed
(and its shadow profiles) before re-inserting. Never touches the 3 real login
accounts (beyond wiring them in) or the 15 songs.
"""
import random
from collections import defaultdict

random.seed(20260719)

SENTINEL = "seed:dev-studio"
N_SONGS = 15

# --- people ------------------------------------------------------------------
# Shadow students (idx 0..10) — no auth.users, user_id NULL, is_shadow.
STUDENTS = [
    ("Maya", "Kowalski"), ("Liam", "Novak"), ("Zofia", "Kaminski"),
    ("Ethan", "Brooks"), ("Amara", "Okafor"), ("Noah", "Bergman"),
    ("Ines", "Marchetti"), ("Kai", "Andersen"), ("Lucia", "Romano"),
    ("Oskar", "Lindqvist"), ("Priya", "Sharma"),
]
# Real student@dev.local occupies student idx 11.
REAL_STUDENT_IDX = len(STUDENTS)            # 11
N_STUDENTS = len(STUDENTS) + 1              # 12

SHADOW_TEACHER = ("Marta", "Zielinski")     # teacher idx 1
# Real teacher@dev.local occupies teacher idx 0.
N_TEACHERS = 2

def uuid_student(i):  return f"5eed57ad-0000-4000-8000-{i:012d}"
def uuid_teacher(i):  return f"5eed7eac-0000-4000-8000-{i:012d}"
def uuid_lesson(i):   return f"5eed1e55-0000-4000-8000-{i:012d}"

def dq(s):  # dollar-quote text
    return f"$q${s}$q$"

STATUSES = ["started", "remembered", "with_author", "mastered"]
STATUS_WEIGHTS = [0.35, 0.30, 0.20, 0.15]
MASTERY_MIN = {"started": (30, 120), "remembered": (120, 300),
               "with_author": (250, 500), "mastered": (400, 900)}

out = []
def w(line=""): out.append(line)

w("-- Generated by gen-dev-studio-seed.py — do not edit by hand; regenerate.")
w("-- Realistic dev studio for StudentDevelopment. Idempotent (tag: %s)." % SENTINEL)
w("BEGIN;")
w("-- Bypass triggers for the whole seed: shadow students have no auth.users row,")
w("-- but song_status_history/notify triggers FK student_id to users and would fail.")
w("-- We insert repertoire directly and set lesson numbers ourselves, so no trigger is needed.")
w("SET session_replication_role = replica;")
w("")
w("-- ===== 1. cleanup prior seed (reverse-FK order) =====")
w(f"DELETE FROM assignments        WHERE description   = '{SENTINEL}';")
w(f"DELETE FROM student_repertoire WHERE teacher_notes = '{SENTINEL}';")
w(f"DELETE FROM lesson_songs       WHERE lesson_id IN (SELECT id FROM lessons WHERE notes = '{SENTINEL}');")
w(f"DELETE FROM lessons            WHERE notes         = '{SENTINEL}';")
w(f"DELETE FROM profiles           WHERE is_development = true AND email LIKE '%@seed.dev.local';")
w("")

w("-- ===== 2. shadow profiles (11 students + 1 teacher) =====")
w("INSERT INTO profiles (id, user_id, email, first_name, last_name, full_name,")
w("                      is_student, is_teacher, is_admin, is_shadow, is_development, student_status)")
rows = []
for i, (fn, ln) in enumerate(STUDENTS):
    email = f"{fn.lower()}.{ln.lower()}@seed.dev.local"
    rows.append(f"('{uuid_student(i)}', NULL, '{email}', {dq(fn)}, {dq(ln)}, {dq(fn+' '+ln)}, "
                f"true, false, false, true, true, 'active')")
tfn, tln = SHADOW_TEACHER
temail = f"{tfn.lower()}.{tln.lower()}@seed.dev.local"
rows.append(f"('{uuid_teacher(1)}', NULL, '{temail}', {dq(tfn)}, {dq(tln)}, {dq(tfn+' '+tln)}, "
            f"false, true, false, true, true, 'active')")
w("VALUES\n" + ",\n".join(rows) + ";")
w("")

w("-- ===== 3. resolve songs + real accounts into temp index tables =====")
w("CREATE TEMP TABLE _songs ON COMMIT DROP AS")
w("  SELECT (row_number() OVER (ORDER BY created_at, id))::int - 1 AS idx, id")
w("  FROM songs WHERE deleted_at IS NULL AND is_draft = false;")
w("")
w("CREATE TEMP TABLE _students (idx int, id uuid) ON COMMIT DROP;")
srows = [f"({i}, '{uuid_student(i)}')" for i in range(len(STUDENTS))]
srows.append(f"({REAL_STUDENT_IDX}, (SELECT id FROM profiles WHERE email = 'student@dev.local'))")
w("INSERT INTO _students VALUES\n  " + ",\n  ".join(srows) + ";")
w("")
w("CREATE TEMP TABLE _teachers (idx int, id uuid) ON COMMIT DROP;")
w("INSERT INTO _teachers VALUES")
w(f"  (0, (SELECT id FROM profiles WHERE email = 'teacher@dev.local')),")
w(f"  (1, '{uuid_teacher(1)}');")
w("")

# --- build lessons -----------------------------------------------------------
# Every student gets 2-5 lessons; teacher 0 (dev teacher) owns ~55% + all of the
# real student's lessons. scheduled_at spread: past 42 days -> future 14 days.
LESSON_TITLES = [
    "Chord transitions", "Strumming patterns", "Fingerpicking intro", "Song study",
    "Barre chords", "Rhythm & timing", "Repertoire review", "Music theory basics",
    "Scale practice", "Performance prep", "Ear training", "Technique clinic",
]
lessons = []   # (lid, t_idx, s_idx, dayoff, title, status, lnum)
lid = 0
pair_num = defaultdict(int)   # (teacher, student) -> running lesson number
for s_idx in range(N_STUDENTS):
    n = random.randint(2, 5)
    for _ in range(n):
        if s_idx == REAL_STUDENT_IDX:
            t_idx = 0
        else:
            t_idx = 0 if random.random() < 0.55 else 1
        dayoff = random.randint(-14, 42)          # >0 past, <0 future
        if dayoff > 0:
            status = "CANCELLED" if random.random() < 0.1 else "COMPLETED"
        else:
            status = "SCHEDULED"
        title = random.choice(LESSON_TITLES)
        pair_num[(t_idx, s_idx)] += 1
        lessons.append((uuid_lesson(lid), t_idx, s_idx, dayoff, title, status, pair_num[(t_idx, s_idx)]))
        lid += 1

w(f"-- ===== 4. lessons ({len(lessons)}) =====")
w("INSERT INTO lessons (id, teacher_id, student_id, scheduled_at, title, status, notes, lesson_teacher_number)")
w("SELECT v.lid::uuid, t.id, s.id, now() - make_interval(days => v.dayoff), v.title,")
w(f"       v.status::lesson_status, '{SENTINEL}', v.lnum")
lrows = [f"('{l[0]}', {l[1]}, {l[2]}, {l[3]}, {dq(l[4])}, '{l[5]}', {l[6]})" for l in lessons]
w("FROM (VALUES\n  " + ",\n  ".join(lrows) + "\n) v(lid, t_idx, s_idx, dayoff, title, status, lnum)")
w("JOIN _teachers t ON t.idx = v.t_idx")
w("JOIN _students s ON s.idx = v.s_idx;")
w("")

# --- lesson_songs: cover every song >= 2 lessons, then random fill ----------
ls_pairs = set()   # (lid_index, song_idx)
# coverage: assign each song to 2-3 distinct lessons
for song_idx in range(N_SONGS):
    for _ in range(random.randint(2, 3)):
        li = random.randrange(len(lessons))
        ls_pairs.add((li, song_idx))
# fill: each lesson gets up to 1-3 songs total
for li in range(len(lessons)):
    have = sum(1 for (a, _) in ls_pairs if a == li)
    for _ in range(random.randint(0, 3 - min(have, 3))):
        ls_pairs.add((li, random.randrange(N_SONGS)))

LS_STATUS = ["to_learn", "started", "remembered", "with_author", "mastered"]
w(f"-- ===== 5. lesson_songs ({len(ls_pairs)}) — trigger auto-creates repertoire =====")
w("INSERT INTO lesson_songs (lesson_id, song_id, status)")
w("SELECT v.lid::uuid, sg.id, v.status::lesson_song_status")
lsrows = []
for (li, song_idx) in sorted(ls_pairs):
    st = random.choices(LS_STATUS, weights=[0.25, 0.3, 0.2, 0.15, 0.1])[0]
    lsrows.append(f"('{uuid_lesson(li)}', {song_idx}, '{st}')")
w("FROM (VALUES\n  " + ",\n  ".join(lsrows) + "\n) v(lid, s_idx, status)")
w("JOIN _songs sg ON sg.idx = v.s_idx")
w("ON CONFLICT (lesson_id, song_id) DO NOTHING;")
w("")

# --- repertoire: overwrite trigger rows + ensure every song has >=2 learners --
rep = {}   # (s_idx, song_idx) -> status
# every song: 2-4 learners with non-to_learn status
for song_idx in range(N_SONGS):
    learners = random.sample(range(N_STUDENTS), random.randint(2, 4))
    for s_idx in learners:
        rep[(s_idx, song_idx)] = random.choices(STATUSES, weights=STATUS_WEIGHTS)[0]
# real student learns ~7 songs across the mastery range
for song_idx in random.sample(range(N_SONGS), 7):
    rep[(REAL_STUDENT_IDX, song_idx)] = random.choices(STATUSES, weights=STATUS_WEIGHTS)[0]

def rep_row(s_idx, song_idx, status):
    lo, hi = MASTERY_MIN[status]
    minutes = random.randint(lo, hi)
    lastdays = random.randint(0, 10)
    startdays = random.randint(30, 90)
    masterdays = random.randint(1, 20) if status == "mastered" else "NULL"
    diff = random.randint(2, 4)
    selfr = {"started": 2, "remembered": 3, "with_author": 4, "mastered": 5}[status]
    prio = random.choice(["high", "normal", "normal", "low"])
    md = masterdays if masterdays == "NULL" else str(masterdays)
    return (f"({s_idx}, {song_idx}, '{status}', {minutes}, {lastdays}, {startdays}, "
            f"{md}::int, {diff}, {selfr}, '{prio}')")

w(f"-- ===== 6. repertoire ({len(rep)}) — overwrites trigger to_learn rows =====")
w("INSERT INTO student_repertoire")
w("  (student_id, song_id, current_status, total_practice_minutes, last_practiced_at,")
w("   started_at, mastered_at, is_active, difficulty_rating, self_rating, priority, teacher_notes)")
w("SELECT s.id, sg.id, v.status::song_progress_status, v.minutes,")
w("       now() - make_interval(days => v.lastdays),")
w("       now() - make_interval(days => v.startdays),")
w("       CASE WHEN v.masterdays IS NULL THEN NULL ELSE now() - make_interval(days => v.masterdays) END,")
w(f"       true, v.diff, v.selfr, v.priority, '{SENTINEL}'")
rprows = [rep_row(s, sg, st) for (s, sg), st in sorted(rep.items())]
w("FROM (VALUES\n  " + ",\n  ".join(rprows)
  + "\n) v(s_idx, sg_idx, status, minutes, lastdays, startdays, masterdays, diff, selfr, priority)")
w("JOIN _students s ON s.idx = v.s_idx")
w("JOIN _songs sg ON sg.idx = v.sg_idx")
w("ON CONFLICT (student_id, song_id) DO UPDATE SET")
w("  current_status = EXCLUDED.current_status,")
w("  total_practice_minutes = EXCLUDED.total_practice_minutes,")
w("  last_practiced_at = EXCLUDED.last_practiced_at,")
w("  started_at = EXCLUDED.started_at,")
w("  mastered_at = EXCLUDED.mastered_at,")
w("  is_active = true,")
w("  difficulty_rating = EXCLUDED.difficulty_rating,")
w("  self_rating = EXCLUDED.self_rating,")
w("  priority = EXCLUDED.priority,")
w(f"  teacher_notes = '{SENTINEL}';")
w("")

# --- assignments -------------------------------------------------------------
A_STATUS = ["not_started", "in_progress", "completed", "overdue"]
A_TITLES = ["Practice the intro", "Memorize the chorus", "Work on transitions",
            "Record a take", "Slow-tempo run-through", "Clean up timing"]
assignments = []
# ~30 assignments, several for the real student
for _ in range(24):
    s_idx = random.randrange(N_STUDENTS)
    t_idx = 0 if (s_idx == REAL_STUDENT_IDX or random.random() < 0.55) else 1
    assignments.append((t_idx, s_idx))
for _ in range(6):  # extra for the real student
    assignments.append((0, REAL_STUDENT_IDX))

w(f"-- ===== 7. assignments ({len(assignments)}) =====")
w("INSERT INTO assignments (teacher_id, student_id, song_id, title, description, status, due_date)")
w("SELECT t.id, s.id, sg.id, v.title, ")
w(f"       '{SENTINEL}', v.status::assignment_status,")
w("       CASE WHEN v.duedays IS NULL THEN NULL ELSE (now() + make_interval(days => v.duedays))::date END")
arows = []
for (t_idx, s_idx) in assignments:
    sg = random.randrange(N_SONGS)
    st = random.choice(A_STATUS)
    duedays = "NULL" if random.random() < 0.3 else str(random.randint(-10, 21))
    dd = duedays if duedays == "NULL" else duedays
    arows.append(f"({t_idx}, {s_idx}, {sg}, {dq(random.choice(A_TITLES))}, '{st}', {dd}::int)")
w("FROM (VALUES\n  " + ",\n  ".join(arows) + "\n) v(t_idx, s_idx, sg_idx, title, status, duedays)")
w("JOIN _teachers t ON t.idx = v.t_idx")
w("JOIN _students s ON s.idx = v.s_idx")
w("JOIN _songs sg ON sg.idx = v.sg_idx;")
w("")

w("SET session_replication_role = DEFAULT;")
w("COMMIT;")
w("")
w("-- summary")
w("SELECT 'students=' || (SELECT count(*) FROM profiles WHERE is_student)")
w("    || ' teachers=' || (SELECT count(*) FROM profiles WHERE is_teacher)")
w("    || ' lessons='  || (SELECT count(*) FROM lessons)")
w("    || ' lesson_songs=' || (SELECT count(*) FROM lesson_songs)")
w("    || ' repertoire=' || (SELECT count(*) FROM student_repertoire)")
w("    || ' assignments=' || (SELECT count(*) FROM assignments);")

print("\n".join(out))
