#!/bin/bash
# Bearer Token Feature Testing Guide

echo "=========================================="
echo "Bearer Token Feature - Testing Checklist"
echo "=========================================="
echo ""

echo "✅ DATABASE"
echo "  - api_keys table: Created"
echo "  - RLS policies: Enabled"
echo "  - Indexes: Created on user_id and key_hash"
echo ""

echo "✅ API ENDPOINTS"
echo "  - GET /api/api-keys: Working (401 without auth)"
echo "  - POST /api/api-keys: Ready (needs auth + name)"
echo "  - DELETE /api/api-keys/[id]: Ready (needs auth + ownership)"
echo ""

echo "✅ DASHBOARD COMPONENTS"
echo "  - BearerTokenDisplay added to DashboardPageContent"
echo "  - BearerTokenDisplay added to AdminDashboardClient"
echo "  - Component loads without errors"
echo ""

echo "=========================================="
echo "TO TEST THE FEATURE:"
echo "=========================================="
echo ""
echo "1. Start dev server (if not running):"
echo "   npm run dev"
echo ""
echo "2. Login to the application:"
echo "   Go to http://localhost:3000"
echo "   Login with your user account"
echo ""
echo "3. Go to dashboard:"
echo "   http://localhost:3000/dashboard"
echo ""
echo "4. Look for the Bearer Token section:"
echo "   - Should be visible below the header"
echo "   - Shows all your existing API keys"
echo "   - Button to generate new token"
echo ""
echo "5. Create a new bearer token:"
echo "   - Click 'Generate New Token'"
echo "   - Give it a name (e.g., 'Test Key')"
echo "   - Copy the generated token (appears once)"
echo ""
echo "6. Test the token with curl:"
echo "   curl -H \"Authorization: Bearer gcrm_your_token_here\" \\"
echo "   http://localhost:3000/api/api-keys"
echo ""
echo "   Should return your list of API keys as JSON"
echo ""
echo "7. Use token in API requests:"
echo "   const response = await fetch('/api/songs', {"
echo "     headers: {"
echo "       'Authorization': \`Bearer \${yourToken}\`"
echo "     }"
echo "   });"
echo ""

echo "=========================================="
echo "DATABASE COMMANDS FOR DEBUGGING:"
echo "=========================================="
echo ""
echo "List all API keys:"
echo "  psql postgresql://postgres:postgres@127.0.0.1:54322/postgres \\"
echo "  -c \"SELECT id, user_id, name, is_active, created_at FROM api_keys;\""
echo ""
echo "Check RLS policies:"
echo "  psql postgresql://postgres:postgres@127.0.0.1:54322/postgres \\"
echo "  -c \"\\dp api_keys\""
echo ""
echo "Check table structure:"
echo "  psql postgresql://postgres:postgres@127.0.0.1:54322/postgres \\"
echo "  -c \"\\d api_keys\""
echo ""

echo "=========================================="
echo "FEATURE READY FOR TESTING ✅"
echo "=========================================="
