import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { NotificationType, NOTIFICATION_TYPE_INFO } from '@/types/notifications';
import { verifyUnsubscribeToken } from '@/lib/notifications/unsubscribe-token';
import { logger } from '@/lib/logger';

/**
 * GET /api/notifications/unsubscribe
 *
 * Accepts a signed HMAC token instead of raw userId + type params to
 * prevent IDOR attacks. Token is generated by generateUnsubscribeToken()
 * and embedded in email footer links.
 *
 * Backward-compat: if legacy userId+type params are present without a
 * token, returns 400 with a migration message instead of silently accepting.
 */
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const token = searchParams.get('token');
  const legacyUserId = searchParams.get('userId');
  const legacyType = searchParams.get('type');

  // Detect legacy (unsigned) link usage and reject with a helpful message
  if (!token && (legacyUserId || legacyType)) {
    return NextResponse.json(
      {
        error: 'legacy_params',
        message:
          'This unsubscribe link is outdated. Please use the link from a recent email, ' +
          'or manage your notification preferences in your account settings.',
      },
      { status: 400 }
    );
  }

  if (!token) {
    return NextResponse.json(
      { error: 'missing_token', message: 'Unsubscribe token is required.' },
      { status: 400 }
    );
  }

  const verified = verifyUnsubscribeToken(token);
  if (!verified) {
    return NextResponse.json(
      {
        error: 'invalid_token',
        message:
          'This unsubscribe link is invalid or has expired (links expire after 30 days).',
      },
      { status: 401 }
    );
  }

  const { userId, type: notificationType } = verified;

  // Validate notification type
  if (!NOTIFICATION_TYPE_INFO[notificationType as NotificationType]) {
    return NextResponse.redirect(
      new URL('/unsubscribe?error=invalid_type', request.url)
    );
  }

  try {
    const supabase = await createClient();

    // Verify user exists
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('id, email')
      .eq('id', userId)
      .single();

    if (profileError || !profile) {
      logger.error('User not found for unsubscribe:', profileError);
      return NextResponse.redirect(
        new URL('/unsubscribe?error=user_not_found', request.url)
      );
    }

    // Update notification preference to disabled
    const { error: updateError } = await supabase
      .from('notification_preferences')
      .update({ enabled: false })
      .eq('user_id', userId)
      .eq('notification_type', notificationType);

    if (updateError) {
      logger.error('Error updating notification preference:', updateError);
      return NextResponse.redirect(
        new URL('/unsubscribe?error=update_failed', request.url)
      );
    }

    return NextResponse.redirect(
      new URL(
        `/unsubscribe?success=true&type=${encodeURIComponent(notificationType)}`,
        request.url
      )
    );
  } catch (error) {
    logger.error('Unsubscribe error:', error);
    return NextResponse.redirect(
      new URL('/unsubscribe?error=server_error', request.url)
    );
  }
}
